### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by tyilo** [steveklabnik/issue2pr#3]
GitHub pull request screenshot:
![](http://i.imgur.com/mO56hQ5.png)

Issues2Pr screenshot:
![](http://i.imgur.com/7DIbGMA.png)

It doesn't work :cry:

**Comment by steveklabnik** [comment]
Bummer. Ill try to look into it.
—

**Comment by deanmalmgren** [comment]
@Tyilo can you confirm that pull request #4 fixes the problem you were having? Do you recall he repository to which you were trying to issue a pull request?

**Comment by tyilo** [comment]
The creator of the repository had a name containing a dash, so this is probably fixed now.
